### PR TITLE
Update Factorio.yaml

### PR DESCRIPTION
**Pull request by Berserker66**
Not tested, just written up in github's editor.

Removed traps, they're bad for async.
Revamped tech costs to be reasonable
added recipe time, tech cost distribution and ramping tech cost

Personally I'd also recommend removing the peaceful mode starts. If someone wants to play with peaceful they can use the server console to change it.

### CODE REVIEW

**Comment by alwaysintreble** [comment]
While I agree with you on the peaceful mode stuff, enough people complain about it that I felt it was only fair to give them the option to start that way without having to enter in a command.

**Comment by t3hf1gm3nt** [comment]
> Personally I'd also recommend removing the peaceful mode starts. If someone wants to play with peaceful they can use the server console to change it.

does the reverse also apply? using console to switch it to non-peaceful? if so: id rather it be all peaceful starts and those who want to deal with biters can turn it on themselves

**Comment by t3hf1gm3nt** [comment]
this probably needs updated with the new factorio things, doesnt it?

**Comment by Berserker66** [comment]
Probably does, good luck, please don't mess it up again.

**Comment by Berserker66** [comment]
> 



> > Personally I'd also recommend removing the peaceful mode starts. If someone wants to play with peaceful they can use the server console to change it.
> 
> does the reverse also apply? using console to switch it to non-peaceful? if so: id rather it be all peaceful starts and those who want to deal with biters can turn it on themselves

No, the thing most people use to turn it peaceful removes the Biters from the map, which is irreversable.

**Comment by t3hf1gm3nt** [comment]
> Probably does, good luck, please don't mess it up again.

no i meant aren't there new options? i dunno jack about factorio
so was wondering if you wanted to update this with said new options before i do anything with this

**Comment by Berserker66** [comment]
This PR's purpose is to unfuck Factorio.

**Pull request merged**
