### PR TITLE
Update SA2 to 0.3.7.

### PR DESCRIPTION
**Pull request by TheT113**
My rationale behind these choices:

Chaos Emeralds can be a bit of a slog and Triforce Hunt-adjacent (more so than Emblems are), so let's leave it out.

Chao Keys and Pipes are doable (and there's a good guide out), but let's keep the chance of them lower. Beetles in general are very easy, but keeping the same random weights for consistency.

For level types, a little bit of variety is good. Keeping Chao missions (Mission 3) in the rotation ensures the Mystic Melodies have a chance to be required, and otherwise the missions are not hard. Ring Missions (Mission 2) are typically very easy. Speed/Mech Mission 4s (Timer) are generally interesting and worth having a chance to show up.

Speed Missions randomly have 2-4 missions each because Speed missions are generally the most fun and interesting. If it rolls 2 or 3, it guarantees there will be variety in the mission type seen; if it rolls 4, at least they will be in random order.

All other missions are 1 or 2, with some variety to allow different mission types to be experienced.

Kart Mission 2 are extremely easy and if Mission Count is rolled 1, the chance that people will only have to do Rings and not the normal run would be a relief.

### CODE REVIEW

**Comment by t3hf1gm3nt** [comment]
i still have yet to play SA2 so i can't really comment on these changes. will leave this up and try to prod some people to weigh in. if theres no major objections will probably just end up merging

**Review by Joethepic — COMMENTED** [review]
For a async I think the mission counts are kinda low for specifically hunt and maybe mech. Though I'm not great at sonic yet but with more time more missions make sense to me and their is already 3 missions in rotation I think random-range-1-3 would work better for hunt.

**Comment by TheT113** [comment]
These are beginner worlds. People who want a want a longer, harder world will be submitting a custom.

The length of a world in an async is immaterial. As long as it isn't possible to go mode it extremely early, the length doesn't matter. The gating does.

**Comment by TheT113** [comment]
Thought about it again. I'll increase the chance to 3 for Mech and Hunting.

**Review by Joethepic — APPROVED** [review]

**Pull request merged**
