### PR TITLE
Update __meta__.yaml: Game weights

### PR DESCRIPTION
**Pull request by ScootyPuffJr1**
Updating game weights

### CODE REVIEW

**Comment by black-sliver** [comment]
I believe we wanted to remove subnautica if it does not find a maintainer? 
Not sure about RL vs. SM. Just looked at /stats and SM seems more popular.

**Comment by Berserker66** [comment]
Subnautica can stay for now, but at some point we need to cut out the server-side compatibility code.

**Comment by ScootyPuffJr1** [comment]
SM definitely has more people than RL (269-156). I wasn't sure if the addition of SMZ3 reduced the number of people willing to play just SM. Both SM and RL had their filler seeds claimed very quickly in the last async.

**Comment by black-sliver** [comment]
```
  Ocarina of Time: 50
  # ...
  Super Metroid: 40
  Rogue Legacy: 60
```
Just feels odd, but if you think your numbers are worth testing, I'm fine with it.

Last async had very few fillers in general. I hope we'll get a higher success rate and more slots this time :)

**Pull request merged**
