### PR TITLE
Bring Super Metroid up to 0.4.3

### PR DESCRIPTION
**Pull request by ScootyPuffJr1**

### CODE REVIEW

**Comment by ScootyPuffJr1** [comment]
I tried using Github Desktop for the first time and may have screwed something up. Hopefully me reverting those other commits (because I failed to create a branch first) doesn't have any impact.

**Comment by t3hf1gm3nt** [comment]
it shooooould be fine when it gets squashed. yeah github desktop can be a bit bunk at times lol
gonna wait to hear silvris's response either here or on discord on their thoughts about the update, but did verify that the yaml's good

**Comment by Silvris** [comment]
Some options were added and not mentioned here, giving my personal opinion on what they should be set to:
```
escape_rando:
    false: 50
    true: 10
relaxed_round_robin_cf: true
```
Rest of the changes look good to me!

**Comment by ScootyPuffJr1** [comment]
Added changes per Silvris

**Pull request merged**
