### PR TITLE
Add Noita

### PR DESCRIPTION
**Pull request by ScipioWright**
I talked over the weighting with the other maintainer, Heinermann, and he was fine with it.

Tried generating with it with higher Noita rates and other games several times, and it worked even with extreme conditions, so looks good to me.

### CODE REVIEW

**Comment by ScootyPuffJr1** [comment]
@ScipioWright Just checking with you if any of these options need to be updated to be up to date with AP version 0.4.2

**Comment by ScipioWright** [comment]
Oh you're totally right, I need to make a minor update to this to add in some of the newer options. I'll do that later today, thank you for the reminder!

**Comment by ScipioWright** [comment]
Converted to draft since I messed with it in-browser. Will test it once I get home and un-draft it then.

**Comment by ScipioWright** [comment]
This is now ready, sorry for the delay!

**Comment by ScootyPuffJr1** [comment]
I've verified that this runs and the game weight seems fine. I don't know enough about the game to comment on option weights, but we've chatted about them in Discord, so they are probably good to go.

**Pull request merged**
