### PR TITLE
Use more acessible settings for new players

### PR DESCRIPTION
**Pull request by Ziktofel**
How I can test generating the game?

### CODE REVIEW

**Comment by Ziktofel** [comment]
In the current async runs all unclaimed fillers so far are the shorts with All in - In these settings All in is significantly harder than other missions

The purpose of this change is to offer fillers accessible to new players

**Comment by Magnemania** [comment]
Short seeds are difficult for new players because they place more difficult missions earlier in the seed and provide fewer extra items beyond the bare minimum logic required to complete the seed.

In an async, the tiny item pool is especially problematic because players receive only a tiny fraction of their items at the beginning; it's very possible for a short seed's only anti-air unit to be stuck at the end of a long game, and the algorithm is unlikely to care, as blocking an entire short seed only blocks ~30 locations.

It is also fundamentally against the spirit of the async to play games on settings intended for <2 hour runs.

Also, **shuffle_protoss** does nothing on vanilla; that trigger is unnecessary.

The only part of this that I agree with is the difficulty rebalancing.  Experienced players should be aware of the /difficulty command, so biasing the seeds even more heavily towards lower difficulties should be fine.  However, I'm somewhat opposed to making Casual an extremely common option, as logic barely applies on Normal and never applies on Casual.

**Comment by Ziktofel** [comment]
What about the increased difficulty of all in in shorter campaigns for new players?

**Comment by Ziktofel** [comment]
Is there a way to reduce the time commitment (from full campaign) without increasing the difficulty of All-in?

**Comment by Ziktofel** [comment]
@Magnemania I think the difficulty problem of shorts applies mainly to gauntlet because you're forced to play certain mission while in Blitz and minigrid you have a way around. Gauntlet could be dropped because of that

I still think that a shorter run that's not difficult has its place in async. In current situation the Blitz has 12 missions and it's the longest without all in. I'm open myself for large grid without `All in` or using somewhat nerfed version of `All in` in shorts

I still believe that Blitz could do a perfect job for a side-game

**Comment by Magnemania** [comment]
Blitz can be completed in under two hours and requires even less logic than the other short seeds; that is entirely against the point of the async.

**Comment by Ziktofel** [comment]
You can either complete fast when your goal is for example Media Blitz (there's cheese) or be in a hard BK for a long time. All depends on what stuff you have early on and cheesable missions

**Comment by Ziktofel** [comment]
Tried the new All-out and with a good inventory it's a great ending for shorter campaigns (large grid, etc) :)

**Comment by t3hf1gm3nt** [comment]
im actually going to close this. i agree with mag's concerns that a lot of this is against what the async is about. if people want shorter campaigns, they can submit customs. and the difficulty change is honestly not that big a deal with the change difficulty command existing.

**Pull request closed without merging**
