### PR TITLE
dont force power stars local for SM64

### PR DESCRIPTION
**Pull request by t3hf1gm3nt**
no one wants to play single player sm64 for a big multiworld

### CODE REVIEW

**Comment by Berserker66** [comment]
should be discussed first, as the change was made as a result of a discussion.

**Comment by t3hf1gm3nt** [comment]
we had the discussion about how sm64 filler seeds should be months ago, and im 99% certain that it was determined that until the star door requirements can be set lower than 50, that forcing local power stars would be unreasonable. im trolling through the discord now to find the relevant conversation

**Comment by t3hf1gm3nt** [comment]
actually here: https://github.com/ArchipelagoMW/AsyncTools/pull/10 you already had discussed this once with scooty when he made them local in the first place, and scooty was also conflicted. i guess we do need to have a rehash of this discussion with the community because a lot of things changed with sm64 since then

**Comment by Joethepic** [comment]
based on the discussion most people be on the side of non local

**Comment by t3hf1gm3nt** [comment]
thats what im getting from the conversation as well

**Comment by t3hf1gm3nt** [comment]
closing this PR because The T has opened one using the new restructure

**Pull request closed without merging**
